set -e
true
true
/root/miniconda3/envs/genomeanalysis/bin/spades-core /mnt/c/Users/chris/OneDrive/Desktop/Christina.txt/spadesout/K21/configs/config.info /mnt/c/Users/chris/OneDrive/Desktop/Christina.txt/spadesout/K21/configs/isolate_mode.info
/root/miniconda3/envs/genomeanalysis/bin/spades-core /mnt/c/Users/chris/OneDrive/Desktop/Christina.txt/spadesout/K33/configs/config.info /mnt/c/Users/chris/OneDrive/Desktop/Christina.txt/spadesout/K33/configs/isolate_mode.info
/root/miniconda3/envs/genomeanalysis/bin/spades-core /mnt/c/Users/chris/OneDrive/Desktop/Christina.txt/spadesout/K55/configs/config.info /mnt/c/Users/chris/OneDrive/Desktop/Christina.txt/spadesout/K55/configs/isolate_mode.info
/root/miniconda3/envs/genomeanalysis/bin/spades-core /mnt/c/Users/chris/OneDrive/Desktop/Christina.txt/spadesout/K77/configs/config.info /mnt/c/Users/chris/OneDrive/Desktop/Christina.txt/spadesout/K77/configs/isolate_mode.info
/root/miniconda3/envs/genomeanalysis/bin/python3 /root/miniconda3/envs/genomeanalysis/share/spades/spades_pipeline/scripts/copy_files.py /mnt/c/Users/chris/OneDrive/Desktop/Christina.txt/spadesout/K77/before_rr.fasta /mnt/c/Users/chris/OneDrive/Desktop/Christina.txt/spadesout/before_rr.fasta /mnt/c/Users/chris/OneDrive/Desktop/Christina.txt/spadesout/K77/assembly_graph_after_simplification.gfa /mnt/c/Users/chris/OneDrive/Desktop/Christina.txt/spadesout/assembly_graph_after_simplification.gfa /mnt/c/Users/chris/OneDrive/Desktop/Christina.txt/spadesout/K77/final_contigs.fasta /mnt/c/Users/chris/OneDrive/Desktop/Christina.txt/spadesout/contigs.fasta /mnt/c/Users/chris/OneDrive/Desktop/Christina.txt/spadesout/K77/first_pe_contigs.fasta /mnt/c/Users/chris/OneDrive/Desktop/Christina.txt/spadesout/first_pe_contigs.fasta /mnt/c/Users/chris/OneDrive/Desktop/Christina.txt/spadesout/K77/strain_graph.gfa /mnt/c/Users/chris/OneDrive/Desktop/Christina.txt/spadesout/strain_graph.gfa /mnt/c/Users/chris/OneDrive/Desktop/Christina.txt/spadesout/K77/scaffolds.fasta /mnt/c/Users/chris/OneDrive/Desktop/Christina.txt/spadesout/scaffolds.fasta /mnt/c/Users/chris/OneDrive/Desktop/Christina.txt/spadesout/K77/scaffolds.paths /mnt/c/Users/chris/OneDrive/Desktop/Christina.txt/spadesout/scaffolds.paths /mnt/c/Users/chris/OneDrive/Desktop/Christina.txt/spadesout/K77/assembly_graph_with_scaffolds.gfa /mnt/c/Users/chris/OneDrive/Desktop/Christina.txt/spadesout/assembly_graph_with_scaffolds.gfa /mnt/c/Users/chris/OneDrive/Desktop/Christina.txt/spadesout/K77/assembly_graph.fastg /mnt/c/Users/chris/OneDrive/Desktop/Christina.txt/spadesout/assembly_graph.fastg /mnt/c/Users/chris/OneDrive/Desktop/Christina.txt/spadesout/K77/final_contigs.paths /mnt/c/Users/chris/OneDrive/Desktop/Christina.txt/spadesout/contigs.paths
true
/root/miniconda3/envs/genomeanalysis/bin/python3 /root/miniconda3/envs/genomeanalysis/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /mnt/c/Users/chris/OneDrive/Desktop/Christina.txt/spadesout/scaffolds.fasta --misc_dir /mnt/c/Users/chris/OneDrive/Desktop/Christina.txt/spadesout/misc --threshold_for_breaking_scaffolds 3
true
